### ISSUE TITLE
Sub Folders Display Incorrectly

### ISSUE THREAD

**Issue by BluStorAdmin** [BluStor/PasswordVault_Android#41]
Multiple sub folders not showing correctly.

I created a folder called Shopping.  Open Shopping.  Create "D1".  Open "D1".  Create "D2".  Open "D2".   Open "D2".  create "D3".    Then navigate back to Shopping folder and "D1" is not visible.

I noticed this before when I tried to delete the root folder and application kept crashing.

![screenshot_2017-08-08-09-21-57](https://user-images.githubusercontent.com/16104568/29076425-218b84ee-7c1b-11e7-83ff-24197c70ed44.png)

**Comment by agildehaus** [comment]
You're not in the Shopping folder in this screenshot, you're in Shopping/D1.

I believe I fixed the crash in bf81a6aa4f1c2994abebc415cb2eebf264be0f45.

**Comment by bravozulu1** [comment]
This is not an issue.  Closing ticket.
