### ISSUE TITLE
Unable to Open Existing Database

### ISSUE THREAD

**Issue by bravozulu1** [BluStor/PasswordVault_Android#43]
Running the BLE branch of git Android Password Vault...   I'm unable to open existing database.  I don't see any errors in Android Studio debug output.   I see entries in the database using Password Vault on the Mac.

**Comment by agildehaus** [comment]
Your card simply isn't paired with standard Bluetooth.  Error messages for this didn't properly show up in certain circumstances due to a threading issue.  Fixed in 784f6a413b8936438435a59a536c7fea8c59e1ba.
